export const REGISTER_NEW_USER = "REGISTER_NEW_USER";
export const REGISTER_NEW_USER_FAILED = "REGISTER_NEW_USER_FAILED";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_FAILED = "LOGIN_USER_FAILED";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED";
export const CLEAR_RESPONSE = "CLEAR_RESPONSE";
export const CLEAR_ERROR = "CLEAR_ERROR";
